### ISSUE TITLE
Illegal character warning from iconv

### ISSUE THREAD

**Issue by nikic** [sabberworm/PHP-CSS-Parser#184]
Parsing the input `@\Afffff` produces an "illegal character" warning from iconv. Possibly this just needs to be suppressed or converted into an exception?

```
#1 /home/nikic/PHP-Fuzzer/example/PHP-CSS-Parser/lib/Sabberworm/CSS/Parsing/ParserState.php(184): iconv('utf-32le', 'utf-8', '\xFF\xFF\xFF\x00')
#2 /home/nikic/PHP-Fuzzer/example/PHP-CSS-Parser/lib/Sabberworm/CSS/Parsing/ParserState.php(85): Sabberworm\CSS\Parsing\ParserState->parseCharacter(true)
#3 /home/nikic/PHP-Fuzzer/example/PHP-CSS-Parser/lib/Sabberworm/CSS/CSSList/CSSList.php(225): Sabberworm\CSS\Parsing\ParserState->parseIdentifier()
#4 /home/nikic/PHP-Fuzzer/example/PHP-CSS-Parser/lib/Sabberworm/CSS/CSSList/CSSList.php(128): Sabberworm\CSS\CSSList\CSSList::parseAtRule(Object(Sabberworm\CSS\Parsing\ParserState))
#5 /home/nikic/PHP-Fuzzer/example/PHP-CSS-Parser/lib/Sabberworm/CSS/CSSList/CSSList.php(70): Sabberworm\CSS\CSSList\CSSList::parseListItem(Object(Sabberworm\CSS\Parsing\ParserState), Object(Sabberworm\CSS\CSSList\Document))
#6 /home/nikic/PHP-Fuzzer/example/PHP-CSS-Parser/lib/Sabberworm/CSS/CSSList/Document.php(28): Sabberworm\CSS\CSSList\CSSList::parseList(Object(Sabberworm\CSS\Parsing\ParserState), Object(Sabberworm\CSS\CSSList\Document))
#7 /home/nikic/PHP-Fuzzer/example/PHP-CSS-Parser/lib/Sabberworm/CSS/Parser.php(56): Sabberworm\CSS\CSSList\Document::parse(Object(Sabberworm\CSS\Parsing\ParserState))
#8 /home/nikic/PHP-Fuzzer/example/target_css_parser.php(11): Sabberworm\CSS\Parser->parse()
```

**Comment by EMDM45** [comment]
I have the same problem:
```
[2020-02-04 09:39:11] (WARN @ /web/core/components/minifyx/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parsing/ParserState.php : 96)
PHP notice: iconv(): Wrong charset, conversion from `utf-32le' to `utf-8' is not allowed
.css:before {content: "";}
```
My code:
```
$parser = new Sabberworm\CSS\Parser('.css:before{content:"\f934"}');
$document = $parser->parse();
echo $document->render();
```
`\f934` - this is unicode from FontAwesome;
